server:
  port: ${FRIEND_TRACKER_PORT:9001}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${FRIEND_TRACKER_DB:friend_tracker}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${FRIEND_TRACKER_DB:friend_tracker}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    baseline-on-migrate: true

  data:
    redis:
      host:
        ${REDIS_HOST:localhost}
      port:
        ${REDIS_PORT:6379}


jwt:
  access-secret: ${JWT_ACCESS_SECRET:eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNzUwNzI2NCwiaWF0IjoxNzE3NTA3MjY0fQ-fCLZlDBNKkJ3-M-a9GBOhGPFH9PCLuzgQKA6Ax73aA}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME:86400000}
  refresh-secret: ${JWT_REFRESH_SECRET:eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNzUwNzI2NCwiaWF0IjoxNzE3NTA3MjY0fQDfPQBjG9cUAFQA9Q3TbHU2m5pRjK5TUV_IXWHPPZNj8}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:604800000}

logging:
  level:
    org:
      springframework:
        security: TRACE

rating:
    max-rating: 10.0
    min-rating: 0.0
    form-weight: 3
    question-weight: 1